<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NODLTP52089263" ignored="0" name="LoginTestCase" tests="1" failures="0" timestamp="28 Sep 2020 08:52:38 GMT" time="4.405" errors="0">
  <testcase name="@BeforeMethod init" time="4.361" classname="core.BaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at core.BaseTest.init(BaseTest.java:72)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod init -->
  <testcase name="@AfterMethod Appclose" time="0.0" classname="core.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod Appclose -->
  <testcase name="wordpress" time="0.0" classname="testcases.LoginTestCase">
    <skipped/>
  </testcase> <!-- wordpress -->
</testsuite> <!-- LoginTestCase -->
